// https://www.youtube.com/watch?v=CfSwxETYAd8&list=PLZUD8BXC8V55DoSZZHUn22miwxCpN1RR3&ab_channel=LudoWic-Topic

import type { Music } from "../types/music";

export const playlist: Music[] = [
  {
    videoId: "CfSwxETYAd8",
    title: "Katana Zero (Ost-Version)",
    author: "ludoWic music",
    duration: "5:48",
  },
  {
    videoId: "CnJsQQWrmiM",
    title: "Sneaky Driver",
    author: "Bill Kiley - Topic",
    duration: "4:40",
  },
  {
    videoId: "foRhG9MNzig",
    title: "You Will Never Know",
    author: "Bill Kiley - Topic",
    duration: "3:16",
  },
  {
    videoId: "0v_RixPSnL0",
    title: "Third District",
    author: "ludoWic music",
    duration: "4:35",
  },
  {
    videoId: "5qRe3yUzgYw",
    title: "Meat Grinder",
    author: "ludoWic music",
    duration: "3:45",
  },
  {
    videoId: "JGRGWUVZqog",
    title: "All for Now",
    author: "ludoWic music",
    duration: "3:25",
  },
  {
    videoId: "EO2lkMIxvUU",
    title: "Overdose",
    author: "ludoWic music",
    duration: "4:27",
  },
  {
    videoId: "Ucaeyx8iE0s",
    title: "Driving Force: Neon Fog",
    author: "Bill Kiley - Topic",
    duration: "4:17",
  },
  {
    videoId: "OtK4k8M7230",
    title: "Chinatown",
    author: "Bill Kiley - Topic",
    duration: "6:03",
  },
  {
    videoId: "faZEYN4KHx0",
    title: "Breath of a Serpent",
    author: "ludoWic music",
    duration: "3:37",
  },
  {
    videoId: "F6E8oBp-MjQ",
    title: "Delusive Bunker",
    author: "ludoWic music",
    duration: "5:18",
  },
  {
    videoId: "DeHp5pPUPzI",
    title: "Full Confession",
    author: "ludoWic music",
    duration: "4:06",
  },
  {
    videoId: "-9s63ZNKSzg",
    title: "Rain on Brick",
    author: "Bill Kiley - Topic",
    duration: "1:25",
  },
  {
    videoId: "OYZMZn9VOs8",
    title: "Silhouette",
    author: "Bill Kiley - Topic",
    duration: "3:36",
  },
  {
    videoId: "50nAD_s7Vho",
    title: "The Sandman 1",
    author: "ludoWic music",
    duration: "0:47",
  },
  {
    videoId: "7O6dHQ_bwW0",
    title: "Nocturne (Co-Composed by Justin Stander)",
    author: "Bill Kiley - Topic",
    duration: "2:14",
  },
  {
    videoId: "5cbrisiV6Sw",
    title: "Volition",
    author: "Bill Kiley - Topic",
    duration: "1:21",
  },
  {
    videoId: "5SfZ69f9MRY",
    title: "Coming Down",
    author: "Bill Kiley - Topic",
    duration: "2:23",
  },
  {
    videoId: "ZVUId81w7KY",
    title: "A Fine Red Mist",
    author: "Bill Kiley - Topic",
    duration: "1:13",
  },
  {
    videoId: "Ir6EAa6w7m4",
    title: "Panoramic Feelings",
    author: "ludoWic music",
    duration: "3:11",
  },
  {
    videoId: "hLCCpkl-Mks",
    title: "Prison Air 1",
    author: "ludoWic music",
    duration: "1:35",
  },
  {
    videoId: "GjQEdk1uWRE",
    title: "Prison Air 2",
    author: "ludoWic music",
    duration: "2:23",
  },
  {
    videoId: "ZLYmRRfjngc",
    title: "Hit the Floor",
    author: "Various Artists - Topic",
    duration: "3:31",
  },
  {
    videoId: "0tGBcKotyb8",
    title: "Tied up at the Moment",
    author: "Bill Kiley - Topic",
    duration: "2:51",
  },
  {
    videoId: "9k2UI8MN5qU",
    title: "A Tense Moment",
    author: "Various Artists - Topic",
    duration: "0:36",
  },
  {
    videoId: "varIRWxEqRk",
    title: "Kill Your TV",
    author: "Bill Kiley - Topic",
    duration: "1:23",
  },
  {
    videoId: "VdFQfaf0yu8",
    title: "Snow",
    author: "Bill Kiley - Topic",
    duration: "2:21",
  },
  {
    videoId: "raoh6SFB0JU",
    title: "End of the Road",
    author: "Bill Kiley - Topic",
    duration: "5:10",
  },
  {
    videoId: "X7a3NgcK7kg",
    title: "The Sandman 2",
    author: "ludoWic music",
    duration: "0:54",
  },
  {
    videoId: "IjmmABnwf7Y",
    title: "Blue Room (Kz-Version)",
    author: "Tunç Çakır - Topic",
    duration: "2:55",
  },
  {
    videoId: "sTXu1T4E1Kg",
    title: "At Home",
    author: "Bill Kiley - Topic",
    duration: "1:37",
  },
  {
    videoId: "rCD9VRCwoSU",
    title: "V Limo (New Donk Shitty)",
    author: "Bill Kiley - Topic",
    duration: "1:43",
  },
  {
    videoId: "Ct2jtIvHnW8",
    title: "Worst Neighbors Ever",
    author: "Bill Kiley - Topic",
    duration: "1:14",
  },
];
